name: Manual Build and Release Electron App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22   # use your Node version
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm  # match your local pnpm version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            pnpm run build:linux
          else
            pnpm run build:win
          fi

      # Optional: Upload build artifacts to GitHub Releases
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          prerelease: ${{ contains(github.ref_name, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
